In [26]:
# 将原始图片资源里的人脸抽取做训练素材

In [27]:
#coding: UTF-8

# 包含库 ######################################################
# 绘制图片需要
from matplotlib import pyplot as plt
import numpy as np
import cv2
from tqdm import tqdm

import os
import sys

# 引入功能库
import extractFace as feExtracter

In [28]:
# 获取文件名(带后缀)
def getFileName(fileUrl):
    filepath, tmpfilename = os.path.split(fileUrl)
    return tmpfilename
# print(getFileName("/home/wilson/aaa.png"))

# 将脸部存储到指定目录
def saveFace(faceInfo, faceImageSavePath):
    # 原图信息
    imagePath = bytes.decode(faceInfo.imagePath)
    image = cv2.imread(imagePath)
    sp = image.shape            #获取图像形状：返回【行数值，列数值】列表
    height = sp[0]                 #图像的高度（行 范围）
    width = sp[1]                 #图像的宽度（列 范围）

    # 修正截取位置
    top = max(0, faceInfo.top)
    bottom = min(height, faceInfo.bottom)
    left = max(0, faceInfo.left)
    right = min(width, faceInfo.right)
    cropImg = image[top:bottom, left:right] #裁剪图像
    fixedImg = cv2.resize(cropImg, (192, 192), interpolation=cv2.INTER_LINEAR)
    #print(111, fixedImg)
    #plt.imshow(cropImg)
    #plt.show()
    
    # 检验解码目录
    if not os.path.exists(faceImageSavePath):                                                                                                                    
         os.makedirs(faceImageSavePath)
    
    imageSavePath = faceImageSavePath+getFileName(imagePath)
    print(imageSavePath)
    cv2.imwrite(imageSavePath,fixedImg)  #写入图像路径
    
# 抽取人脸
def extractFace(instance, nodeName, dirPath, faceImageSavePath):
    response = feExtracter.extractFace(instance, dirPath)
    if response.count < 1:
        print("no any faces extracted")
    else:
        print(nodeName, response.count, "face extracted")
        for k in tqdm(range(response.count)):
            e = response.elems[k]
            saveFace(e, faceImageSavePath + nodeName + "/")
        feExtracter.releaseFaceExtractResponse(instance, response)

In [29]:
# 配置原始资源目录，和人脸存放目录
rawImagePath = '/home/wilson/workstation/TFResFaceEmotion/raw/'
faceImageSavePath = '/home/wilson/workstation/TFResFaceEmotion/emotions/'

# 创建实例
instance = feExtracter.createInstance()

# 遍历原始图片的根目录
for nodeName in os.listdir(rawImagePath):
    nodePath = rawImagePath + nodeName
    if os.path.isdir(nodePath): # 这是表情目录
        extractFace(instance, nodeName, nodePath, faceImageSavePath)

feExtracter.releaseInstance(instance)
print("Done")

100%|██████████| 23/23 [00:00<00:00, 602.11it/s]

sad 23 face extracted
111 [[[ 35  43  84]
  [ 38  42  84]
  [ 41  41  78]
  ...
  [ 26  26  72]
  [ 26  26  72]
  [ 26  26  72]]

 [[ 35  43  84]
  [ 38  42  84]
  [ 42  42  78]
  ...
  [ 26  26  72]
  [ 26  26  72]
  [ 26  26  72]]

 [[ 37  46  85]
  [ 40  43  85]
  [ 43  42  79]
  ...
  [ 27  26  72]
  [ 27  26  72]
  [ 28  26  72]]

 ...

 [[120 118 124]
  [127 124 132]
  [124 120 131]
  ...
  [ 34  31  80]
  [ 35  32  81]
  [ 36  33  80]]

 [[131 129 136]
  [134 131 140]
  [128 124 135]
  ...
  [ 34  31  80]
  [ 34  32  80]
  [ 33  33  81]]

 [[137 133 142]
  [139 135 146]
  [136 132 144]
  ...
  [ 32  32  79]
  [ 31  31  79]
  [ 30  30  78]]]
/home/wilson/workstation/TFResFaceEmotion/emotions/sad/sad (7).jpg
111 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 254 254]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 254 


100%|██████████| 21/21 [00:00<00:00, 595.90it/s]

happy 21 face extracted
111 [[[250 253 244]
  [251 254 245]
  [251 254 245]
  ...
  [249 247 239]
  [249 247 239]
  [249 247 239]]

 [[250 253 244]
  [251 254 245]
  [251 254 245]
  ...
  [247 248 239]
  [247 248 239]
  [247 248 239]]

 [[250 253 244]
  [251 254 245]
  [251 254 245]
  ...
  [247 248 239]
  [247 248 239]
  [247 248 239]]

 ...

 [[  7  10  15]
  [ 10  13  17]
  [ 14  18  21]
  ...
  [ 63  97 162]
  [ 58  91 155]
  [ 49  82 147]]

 [[ 10  13  17]
  [ 11  14  18]
  [ 15  18  22]
  ...
  [ 65  97 162]
  [ 58  90 155]
  [ 49  81 146]]

 [[ 14  17  21]
  [ 13  16  20]
  [ 13  16  20]
  ...
  [ 63  96 159]
  [ 57  88 152]
  [ 49  81 144]]]
/home/wilson/workstation/TFResFaceEmotion/emotions/happy/happy (7).jpg
111 [[[ 55  41  35]
  [ 57  42  35]
  [ 59  43  35]
  ...
  [ 54  42  40]
  [ 58  45  43]
  [ 61  48  46]]

 [[ 54  41  35]
  [ 57  42  36]
  [ 60  43  36]
  ...
  [ 55  43  41]
  [ 59  46  44]
  [ 62  49  47]]

 [[ 51  39  33]
  [ 55  41  35]
  [ 59  43  36]
  ...
  [ 5


100%|██████████| 11/11 [00:00<00:00, 571.25it/s]

fear 11 face extracted
111 [[[ 24  31  51]
  [ 24  31  51]
  [ 24  31  51]
  ...
  [250 255 250]
  [252 255 251]
  [253 255 251]]

 [[ 24  31  51]
  [ 24  31  51]
  [ 24  31  51]
  ...
  [247 252 248]
  [249 253 248]
  [250 253 249]]

 [[ 25  32  52]
  [ 25  32  52]
  [ 25  33  53]
  ...
  [241 247 243]
  [243 248 244]
  [244 249 244]]

 ...

 [[190 164 139]
  [190 164 139]
  [189 164 140]
  ...
  [153 145 146]
  [154 146 149]
  [154 147 150]]

 [[192 165 140]
  [192 165 140]
  [191 165 141]
  ...
  [154 146 148]
  [154 147 150]
  [155 148 151]]

 [[193 166 140]
  [193 166 140]
  [192 166 141]
  ...
  [154 147 148]
  [155 147 150]
  [155 148 151]]]
/home/wilson/workstation/TFResFaceEmotion/emotions/fear/fear (6).jpg
111 [[[ 56  20  22]
  [ 49  16  19]
  [ 45  14  16]
  ...
  [ 93  38  36]
  [ 97  41  39]
  [102  46  41]]

 [[ 57  21  22]
  [ 49  17  18]
  [ 45  14  15]
  ...
  [ 83  29  28]
  [ 88  32  31]
  [ 95  40  35]]

 [[ 57  21  23]
  [ 49  17  18]
  [ 45  14  15]
  ...
  [ 73  


100%|██████████| 21/21 [00:00<00:00, 620.05it/s]

anger 21 face extracted
111 [[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 1  1  1]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 2  2  2]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 3  3  3]]

 ...

 [[13  8  9]
  [15 10 11]
  [16 11 12]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[11  5  6]
  [13  8  9]
  [15 11 12]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 6  1  2]
  [ 8  3  4]
  [11  6  7]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]
/home/wilson/workstation/TFResFaceEmotion/emotions/anger/anger (21).jpg
111 [[[ 82  95  93]
  [ 83  96  94]
  [ 83  96  94]
  ...
  [  4   4   4]
  [  3   3   3]
  [  3   3   3]]

 [[ 82  95  93]
  [ 83  96  94]
  [ 83  96  94]
  ...
  [  6   6   6]
  [  6   6   6]
  [  6   6   6]]

 [[ 82  95  93]
  [ 83  96  94]
  [ 83  96  94]
  ...
  [  8   8   8]
  [  8   8   8]
  [  7   7   7]]

 ...

 [[121 121 121]
  [143 143 143]
  [151 151 151]
  ...
  


100%|██████████| 3/3 [00:00<00:00, 618.45it/s]

disgust 3 face extracted
111 [[[ 41  39  39]
  [ 42  40  40]
  [ 45  43  43]
  ...
  [ 44  42  42]
  [ 43  41  41]
  [ 43  41  41]]

 [[ 41  39  39]
  [ 43  41  41]
  [ 45  43  43]
  ...
  [ 44  42  42]
  [ 42  40  40]
  [ 42  40  40]]

 [[ 42  40  40]
  [ 43  41  41]
  [ 45  43  43]
  ...
  [ 44  42  42]
  [ 41  39  39]
  [ 39  37  37]]

 ...

 [[ 33  34  33]
  [ 34  35  33]
  [ 36  37  35]
  ...
  [139 139 140]
  [172 172 173]
  [188 188 188]]

 [[ 36  36  36]
  [ 36  36  36]
  [ 37  37  36]
  ...
  [134 135 136]
  [170 169 171]
  [187 186 187]]

 [[ 37  37  37]
  [ 37  37  37]
  [ 37  37  36]
  ...
  [132 133 134]
  [168 168 170]
  [186 185 187]]]
/home/wilson/workstation/TFResFaceEmotion/emotions/disgust/disgust (5).jpg
111 [[[ 34  33  43]
  [ 29  27  39]
  [ 19  17  29]
  ...
  [  4   4   4]
  [  5   5   5]
  [  6   6   6]]

 [[ 38  37  47]
  [ 27  25  37]
  [ 18  16  28]
  ...
  [  4   4   4]
  [  4   4   4]
  [  5   5   5]]

 [[ 31  31  40]
  [ 20  18  30]
  [ 23  21  32]
  ...
